### PR TITLE
Configuration improvements

### PR DESCRIPTION
**Pull request by kbence**
This changes makes `knife-cssh` more configurable by letting to set the user and the command to use.
#### Examples

Set the user used for ssh:

``` bash
knife cssh summon -l my-wonderful-user fqdn:*.example.com
```

Use a different implementation than cssh/csshX:

``` bash
knife cssh summon -c tmux-cssh name:web*
```

### CODE REVIEW

**Comment by rottenbytes** [comment]
Hi,

Thanks for contributing ! I made a few comments to your code

**Comment by kbence** [comment]
Hi! Should I bump the version as well (or will you do it)?

**Comment by rottenbytes** [comment]
Go ahead, bump it :)

**Comment by kbence** [comment]
Done

**Comment by rottenbytes** [comment]
Great thanks !

**Pull request merged**
